"use client";
import { FormEvent, useState } from "react";
import { apiFetch, authHeaders } from "./apiClient";

export default function ContentCreator({onCreated}:{onCreated?:()=>void}){
  const [kind,setKind]=useState<"blog"|"project">("blog"); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;const f=new FormData(form);try{const r=await apiFetch("/admin/content",{method:"POST",headers:authHeaders(),body:JSON.stringify({kind,title:f.get("title"),description:f.get("description"),body:f.get("body"),category:f.get("category"),visibility:f.get("visibility"),tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),technologies:String(f.get("technologies")||"").split(",").map(x=>x.trim()).filter(Boolean)})});const d=await r.json();if(r.ok){setStatus(`${kind === "blog" ? "Article" : "Project"} created.`);form.reset();onCreated?.()}else setStatus(d.detail||"Could not create content.");}catch{setStatus("The admin API is offline. Nothing was created.");}finally{setBusy(false)}}
  return <section className="content-creator"><p className="eyebrow">CREATE CONTENT</p><h2>New blog or project.</h2><form onSubmit={submit}><label>Type<select value={kind} onChange={e=>setKind(e.target.value as "blog"|"project")}><option value="blog">Blog / article</option><option value="project">Project</option></select></label><label>Visibility<select name="visibility" defaultValue="public"><option value="public">Public</option><option value="semi-private">Semi-private</option><option value="private">Private</option></select></label><label>Title<input name="title" required/></label><label>Summary<input name="description" required/></label><label>{kind==="blog"?"Article body":"Project features (one per line)"}<textarea name="body" rows={6}/></label><label>Category<input name="category" defaultValue={kind==="blog"?"Leadership":"General"}/></label><label>{kind==="blog"?"Tags (comma separated)":"Technologies (comma separated)"}<input name={kind==="blog"?"tags":"technologies"}/></label><button disabled={busy} className="button button-dark">{busy?"Creating…":`Create ${kind === "blog" ? "article" : "project"} ↗`}</button>{status&&<p className="form-status">{status}</p>}</form></section>;
}
